name: Github Page Deploy Frontend Workflow

on:
  push:
    paths:
    - 'quickfita-frontend/**'
    - '.github/workflows/deploy-frontend.yaml'
    branches: [main]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quickfita-frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - run: yarn build
        env:
          REACT_APP_BACKEND_URL: https://api.quickfita.us.to
      - name: Apply site config
        run: |-
          touch build/.nojekyll
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v1
        with:
          target_branch: gh-pages
          build_dir: quickfita-frontend/build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


